In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import f1_score
d=pd.read_csv("../Data/Cleandata.csv")


In [ ]:
from sklearn.model_selection import train_test_split, GridSearchCV
x=d[['Year','Distance(mi)','TimeDiff','Temperature(F)','Wind_Chill(F)','Visibility(mi)','Traffic_Signal','Start_Lat','Start_Lng']]
y=d['Severity']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
x_train_small = x_train[:5000]
y_train_small = y_train[:5000]
parameters = [{"kernel": ["linear", "rbf", "sigmoid"], "C": [.2, .5, .8, 1.]}, {"kernel": ["poly"], "C": [.2, .5, .8, 1.], "degree": [2, 3, 4]}]
svc = svm.SVC(verbose = 0, random_state = 42, shrinking = False)
grid = GridSearchCV(svc, parameters, verbose = 0, n_jobs = -1)

grid.fit(x_train_small,y_train_small)
print("Best parameters scores:")
print(grid.best_params_)
best_params = grid.best_params_
print("Train score: ", grid.score(x_train_small, y_train_small))

In [3]:

svc = svm.SVC(verbose = 0, random_state = 42, shrinking = False, C=0.5, kernel = 'linear')
svc.fit(x_train, y_train)
print("Train score:", svc.score(x_train, y_train))
print("Validation score:", svc.score(x_test, y_test))

In [ ]:
y_pred = svc.predict(x_test)
accuracy= accuracy_score(y_test, y_pred)
conf = confusion_matrix(y_true=y_test, y_pred=y_pred)
f1= f1_score(y_test, y_pred, average="macro")

In [ ]:
print(accuracy)
print(conf)
print(f1)

0.6816666666666666
[[   0   10    0    0]
 [   0 7830   72    0]
 [   0 3735  350    0]
 [   0    2    1    0]]
0.2398055526591944
